allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  bufferutil: true
  es5-ext: true
  esbuild: true
  utf-8-validate: true
overrides:
  http-proxy-middleware: ^3.0.5
  '@rollup/plugin-terser': 1.0.0
  tmp: 0.2.5
shamefullyHoist: true
strictPeerDependencies: false
resolutionMode: highest
