allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  bufferutil: true
  core-js: true
  es5-ext: true
  esbuild: true
  lightningcss: true
  rolldown: true
  unrs-resolver: true
  utf-8-validate: true
overrides:
  esbuild: 0.28.1
  http-proxy-middleware: ^3.0.5
  '@rollup/plugin-terser': 1.0.0
  postcss: ^8.5.18
  tmp: 0.2.7
  '@lhci/cli@0.15.1>uuid': 11.1.1
  'vite-plugin-top-level-await@1.6.0>uuid': 11.1.1
peerDependencyRules:
  allowedVersions:
    madge>typescript: '6'
strictPeerDependencies: false
resolutionMode: highest
minimumReleaseAgeExclude:
  - '@fedimint/core@0.0.0-canary-bdba63f3b69629f2b7bff73cf25589bd16332838'
  - '@fedimint/fedimint-client-wasm-bundler@0.0.0-canary-bdba63f3b69629f2b7bff73cf25589bd16332838'
  - '@fedimint/transport-web@0.0.0-canary-bdba63f3b69629f2b7bff73cf25589bd16332838'
  - '@fedimint/types@0.0.0-canary-bdba63f3b69629f2b7bff73cf25589bd16332838'
