allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  bufferutil: true
  es5-ext: true
  esbuild: true
  utf-8-validate: true
overrides:
  http-proxy-middleware: ^3.0.5
  '@rollup/plugin-terser': 1.0.0
  tmp: 0.2.5
shamefullyHoist: true
strictPeerDependencies: false
resolutionMode: highest
minimumReleaseAgeExclude:
  - '@fedimint/core@0.0.0-canary-69fdcb1e726a49e7bb7e6e83a2b7e8525abda10f'
  - '@fedimint/fedimint-client-wasm-bundler@0.0.0-canary-69fdcb1e726a49e7bb7e6e83a2b7e8525abda10f'
  - '@fedimint/transport-web@0.0.0-canary-69fdcb1e726a49e7bb7e6e83a2b7e8525abda10f'
  - '@fedimint/types@0.0.0-canary-69fdcb1e726a49e7bb7e6e83a2b7e8525abda10f'
