import { defineBoot } from '#q-app/wrappers'
import { IconSet } from 'quasar'
import {
  matAccountBalance,
  matAccountBalanceWallet,
  matAccountCircle,
  matAdd,
  matAddCircle,
  matArrowBack,
  matArrowDownward,
  matArrowForward,
  matArrowUpward,
  matBackup,
  matBackspace,
  matBolt,
  matCheck,
  matCheckCircle,
  matChevronRight,
  matClear,
  matClose,
  matCode,
  matContentCopy,
  matContentPaste,
  matDelete,
  matDescription,
  matError,
  matErrorOutline,
  matExpandMore,
  matFlashOn,
  matFlashlightOff,
  matFlashlightOn,
  matForum,
  matGroups,
  matHome,
  matInfo,
  matLogout,
  matOpenInNew,
  matPermContactCalendar,
  matPublic,
  matPublicOff,
  matQrCodeScanner,
  matRadioButtonUnchecked,
  matRefresh,
  matRouter,
  matSearch,
  matSearchOff,
  matSettings,
  matSettingsBackupRestore,
  matShare,
  matShield,
  matSwapHoriz,
  matVerified,
  matVisibility,
  matWarning,
  matCurrencyBitcoin,
} from '@quasar/extras/material-icons'

const iconMap: Record<string, string> = {
  account_balance: matAccountBalance,
  account_balance_wallet: matAccountBalanceWallet,
  account_circle: matAccountCircle,
  add: matAdd,
  add_circle: matAddCircle,
  arrow_back: matArrowBack,
  arrow_downward: matArrowDownward,
  arrow_forward: matArrowForward,
  arrow_upward: matArrowUpward,
  backup: matBackup,
  backspace: matBackspace,
  bolt: matBolt,
  check: matCheck,
  check_circle: matCheckCircle,
  chevron_right: matChevronRight,
  clear: matClear,
  close: matClose,
  code: matCode,
  content_copy: matContentCopy,
  content_paste: matContentPaste,
  delete: matDelete,
  description: matDescription,
  error: matError,
  error_outline: matErrorOutline,
  expand_more: matExpandMore,
  flash_on: matFlashOn,
  flashlight_off: matFlashlightOff,
  flashlight_on: matFlashlightOn,
  forum: matForum,
  groups: matGroups,
  home: matHome,
  info: matInfo,
  logout: matLogout,
  open_in_new: matOpenInNew,
  perm_contact_calendar: matPermContactCalendar,
  public: matPublic,
  public_off: matPublicOff,
  qr_code_scanner: matQrCodeScanner,
  radio_button_unchecked: matRadioButtonUnchecked,
  refresh: matRefresh,
  router: matRouter,
  search: matSearch,
  search_off: matSearchOff,
  settings: matSettings,
  settings_backup_restore: matSettingsBackupRestore,
  share: matShare,
  shield: matShield,
  swap_horiz: matSwapHoriz,
  verified: matVerified,
  visibility: matVisibility,
  warning: matWarning,
  currency_bitcoin: matCurrencyBitcoin,
}

export default defineBoot(() => {
  IconSet.iconMapFn = (iconName) => {
    const icon = iconMap[iconName]
    return icon !== undefined ? { icon } : undefined
  }
})
