# Derived from https://github.com/fedimint/fedimint-web-sdk (MIT License)

name: Setup Nix
description: Sets up nix for running tests with devimint



runs:
  using: 'composite'
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@V27
      with:
        nix_path: nixpkgs=channel:nixos-23.11
        extra_nix_config: |
          connect-timeout = 15
          stalled-download-timeout = 15

    - name: Setup Cachix
      uses: cachix/cachix-action@v15
      with:
        name: fedimint
      continue-on-error: true

    - name: Expose fedimint ref, Node, PNPM from dev shell
      shell: bash
      run: |
        nix develop --accept-flake-config --command bash << 'EOF'
          echo "FEDIMINT_REF=${{ env.FEDIMINT_REF }}" >> $GITHUB_ENV

          NODE_BIN_DIR=$(dirname "$(which node)")
          PNPM_BIN_DIR=$(dirname "$(which pnpm)")

          echo "$NODE_BIN_DIR"  >> $GITHUB_PATH
          echo "$PNPM_BIN_DIR" >> $GITHUB_PATH
        EOF
