name: Actionlint

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read
  checks: write

jobs:
  actionlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Lint GitHub Actions
        uses: reviewdog/action-actionlint@v1.72.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          fail_level: error