name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Nix
        uses: ./.github/actions/setup-nix

      - name: Install dependencies
        run: pnpm install

      - name: Run Vitest
        run: pnpm test:unit:ci
      
      - name: Install playwright browsers
        run: pnpm exec playwright install --with-deps

      - name: Run Playwright
        run: pnpm test:e2e
